### ISSUE TITLE
Save as image missing

### ISSUE THREAD

**Issue by DesignMonkey** [prjseal/ImageFilter#13]
Is it just me or is the Save as image button missing? I tried  installing from NuGet and Umbraco Packages, and the button is  ? 

And if I hit save on the image nothing happens. So it doesn't seem to do anything right now? :)

**Comment by prjseal** [comment]
Hi @DesignMonkey 
At the time when this was created the save image api for Umbraco 8 seemed to be broken so we hid the button to save as new image until v8 got fixed. Now there have been a few releases of v8 I will take a look at this content app again with @NikRimington and see if we can get it all working.

**Comment by DesignMonkey** [comment]
Wow. Looks great :) I really like this package. Perfect for my clients which doesn't always has the photoshop skills. So when they can't save but only see, they feel a little cheated ;)

**Comment by prjseal** [comment]
@DesignMonkey I've just finished making the Save as new image work. You can update the package in nuget to version 1.0.2 https://www.nuget.org/packages/ImageFilter/1.0.2

**Comment by DesignMonkey** [comment]
Wow thanks. I will give it a spin later tonight :)

**Comment by prjseal** [comment]
Last night I also added the ability to overwrite the existing image

**Comment by prjseal** [comment]
And finally I have added the ability to apply multiple settings at the same time. E.g. more brightness, with a black and white filter and then flipped horizontally.
