### ISSUE TITLE
App does not appear to be working for Editors, while it works for Administrators

### ISSUE THREAD

**Issue by DanielOor365** [prjseal/ImageFilter#15]
![image](https://user-images.githubusercontent.com/32175267/70058947-5082a280-15f9-11ea-876d-b9257c1290a9.png)

Hi team,
Thanks for your useful package!

When accessing the package as an Administrator, I have no issues at all.
However, when I try to make similar changes as an editor, so without the Admin privileges, I get an error - see pic above.
As you can see, no image is present, and the image it tries to load is 
<img src="{{vm.mediaUrl}}"
This is the HTML, as one can see from the Chrome DevTools.
I also have 7 Errors - screenshot below.
Any help would be appreciated! 

Daniel

![image](https://user-images.githubusercontent.com/32175267/70060021-38ac1e00-15fb-11ea-8923-69e5921c7cb7.png)

**Comment by NikRimington** [comment]
Hey @DanielOor365 ,

Thanks for the detailed bug report. Could you confirm what version of Umbraco v8 you are running so we can investigate it further for you? It's not something we've come across in our testing.

Thanks

Nik

**Comment by DanielOor365** [comment]
Latest formal version: 8.3.0

**Comment by NikRimington** [comment]
Thanks :-) Will test and get back to you :-)

**Comment by prjseal** [comment]
Had a quick look as I have the repo already. Seems like there is a minor bug with Umbraco v8.

I can get around it though with a small fix. 

Will release it tonight.

**Comment by DanielOor365** [comment]
Thanks Paul for your quick help :-)

**Comment by prjseal** [comment]
Fixed, deployed to Our Umbraco and waiting for NuGet to update. 

version 1.0.5 now released.

**Comment by DanielOor365** [comment]
Hi team,
Thanks Paul for your prompt intervention. I can now see and somewhat use the app.
But now I have other bugs, as the filter not always works with Rotating:
(and rotating is the main reason for having this package: a bug in iOS most of the time rotates the picture 90deg for vertical pictures when uploading them in Umbraco)
* If I rotate only, and want to _override_ the original image, if fails: it reverts to the original.
  If I rotate and e.g. change brightness, it sometimes works...
  But after that, I cannot change to one side - it blocks, and rotating 180 brings it back to the original...
* If I rotate only, and want _to create a new image_, that works. And from there, I can rotate as it should.
Could you please have a look at that, as it is will be very confusing for an editor.
Thanks!

**Comment by prjseal** [comment]
Hi Daniel
If you overwrite an existing image it might look like it hasn’t been saved but it is because the browser is caching the original image. If you refresh without caching it should show correctly.

Cheers

Paul

**Comment by DanielOor365** [comment]
Hi Paul,
I played a bit, and got completely stuck: needed to reboot and re-install to get everything working again. But now everything seems to work. except for the overwrite, which sometimes indeed does not refresh... Thanks for that tip!
One really small thing maybe: once you open an image, you get a 404 error for https://newborn.localtest.me/XXXXX/%7B%7Bvm.previewMediaUrl%7D%7D.
But I definitively can live with that!
Thanks again!
Daniel
